Auth
jykuo-love-shiritori/twp pull request #113
Opened 2023-12-27 17:50 UTC by x06lan

Ex. Resolves #106 #107

### Changes

* when backend sever start will add admin account if did not have any admin account in database 
* script add and remove test data (will add or delete image file in minio as well)
* add auth middleware to identify username and role

> [!CAUTION]  
> After merge this PR most API( beside `general` API) will reponse `401` If not have auth token in header

### Testing Approach (if unconventional)

> [!IMPORTANT]  
> add this to .env
> ```
> TWP_ADMIN_USER=admin 
> TWP_ADMIN_PASSWORD=Secret@123
> ```

```golang
// add this code to main.go insert Data
script.InsertInitData(db, mc, context.Background(), "./data.json")
// add this code to main.go delete Data
script.DeleteInitData(db, mc, context.Background(), "./data.json")
```
due to minio issues currently only localhost can access image by presigned url 
```bash
docker-compose up postgres minio 
npm run build 
go run ./
```
check have admin account in database
![screenshot-2023-12-28-01-41-39](https://github.com/jykuo-love-shiritori/twp/assets/52856456/ab68496d-dd4c-4cbe-8ebf-447da2519ba9)

2023-12-28 13:50 UTC, Error0229 commented on db/queries/admin.sql
> +    TRUE AS "enable5d"
syntax error

2023-12-28 13:50 UTC, Error0229 commented on test/db/main.go
Is this file necessary to exist?

2023-12-28 14:31 UTC, kryr34 requested changes
plz remove reformated-SQL-string

2023-12-30 08:58 UTC, NOOBDY requested changes

2023-12-30 08:58 UTC, NOOBDY commented on db/queries/admin.sql
> +    TRUE AS "enable5d"
is this a typo

2023-12-30 08:58 UTC, NOOBDY commented on main.go
> +	// script.DeleteInitData(db, mc, context.Background(), "./data.json")
does this need to be here

2023-12-30 08:58 UTC, NOOBDY commented on pkg/script/main.go
make this into a separate executable

2024-01-02 06:30 UTC, NOOBDY commented on go.mod
run `go mod tidy` here

2024-01-02 06:38 UTC, NOOBDY requested changes

2024-01-02 06:38 UTC, NOOBDY commented on test/db/main.go
why delete this

2024-01-02 07:30 UTC, x06lan commented on test/db/main.go
since `go run script/main.go load data.json` can test db load data there is no need to keep this file

2024-01-02 07:46 UTC, NOOBDY commented on test/db/main.go
this file is for testing if inserting data works, it serves a different purpose

2024-01-02 21:35 UTC, NOOBDY approved these changes

2024-01-03 00:48 UTC, Error0229 approved these changes
WOMM

2024-01-03 07:48 UTC, ntut-rick reviewed
Dismiss change request

2024-01-03 07:50 UTC, kryr34 reviewed
Dismiss change request

2024-01-03 07:50 UTC, kryr34 approved these changes
Dismiss change request

2024-01-03 13:56 UTC, UGisBusy commented
login with admin and passing auth header get 403 ( for many apis
add this thing:
```
Authorization: `Bearer ${token}`,
```

2024-01-04 02:40 UTC, KatoToyoki approved these changes
backend WOMM while frontend is broken, we will fix after it merged

2024-01-04 05:29 UTC, merged