[backend] more swagger
jykuo-love-shiritori/twp pull request #122
Opened 2023-12-28 16:34 UTC by x06lan

Ex. Resolves #121

### Changes
* fix swagger parameter type
* GET /seller/product/{id} return expire_date

### Testing Approach (if unconventional)

1. [POST /seller/coupon/{id}/tag](http://localhost:8080/swagger///index.html#/Shop/post_seller_coupon__id__tag)
2. [POST /seller/product/{id}/tag](http://localhost:8080/swagger///index.html#/Shop/post_seller_product__id__tag)
3. [GET /seller/product/{id}](http://localhost:8080/swagger///index.html#/Shop/get_seller_product__id_)

2023-12-28 16:46 UTC, KatoToyoki submitted a review, later dismissed

2023-12-28 17:20 UTC, NOOBDY requested changes

2023-12-28 17:20 UTC, NOOBDY commented on pkg/router/seller/product.go
> +// @Param			enabled		formData	string	true	"enabled"		default(true)
```suggestion
// @Param			enabled		formData	bool	true	"enabled"		default(true)
```

2023-12-29 13:36 UTC, NOOBDY approved these changes

2023-12-29 16:31 UTC, KatoToyoki approved these changes

2023-12-29 16:31 UTC, merged