[frontend] Shop Route fix
jykuo-love-shiritori/twp pull request #141
Opened 2024-01-07 11:12 UTC by UGisBusy

There's a issue that the function associate to "user view shop" before is not complete and wrong.

### Changes
- user can now view product list in home page
- user can navigate to shop where the product is from
- the shop page now show the real things ( in ur db )
  - shop icon, shop desc, products count
  - click view shop to view product ( and click the product item to view detail
  - click coupon to view shop coupon ( error, see below)

### Testing Approach (if unconventional)
```sh
docker compose up --build
```
- click ``more`` in the product in main page
- go to the shop from the detial product

### Additional context
im not very sure what's cause this
- shop coupon error (500 for user, 403 for admin)

ill add ``add to cart`` function after this merge.

2024-01-07 21:19 UTC, NOOBDY commented on frontend/src/components/CouponItemShowShop.tsx
> +    queryKey: ['userGetSjopCouponDetail', couponId],
```suggestion
    queryKey: ['userGetShopCouponDetail', couponId],
```

2024-01-07 21:26 UTC, NOOBDY approved these changes, later dismissed

2024-01-08 06:20 UTC, UGisBusy reviewed
metro mobile coding

2024-01-08 06:20 UTC, UGisBusy commented on frontend/src/pages/user/shop/index.tsx
> +                <TButton text='Explore Shop' action={`/shop/${sellerName}/shop`} />
```suggestion
                <TButton text='Explore Shop' action={`/shop/${sellerName}/products`} />
```

2024-01-08 06:20 UTC, UGisBusy commented on frontend/src/App.tsx
>                <Route path='shop' element={<Shop />} />
```suggestion
              <Route path='products' element={<Shop />} />
```

2024-01-08 06:21 UTC, UGisBusy commented
shit i fucked up

2024-01-08 08:12 UTC, Error0229 submitted a review, later dismissed
womm

2024-01-08 17:21 UTC, KatoToyoki requested changes

2024-01-08 17:21 UTC, KatoToyoki commented on frontend/src/pages/discover/[goodsID].tsx
> +  image_url: string;
```suggestion
 product_image_url: string;
```

2024-01-08 17:21 UTC, KatoToyoki commented on frontend/src/pages/discover/[goodsID].tsx
> +              <img src={data.image_url} alt='File preview' style={GoodsImgStyle} />
```suggestion
              <img src={data.product_image_url} alt='File preview' style={GoodsImgStyle} />
```

2024-01-08 17:43 UTC, KatoToyoki approved these changes

2024-01-08 17:43 UTC, UGisBusy commented
wrong person lul

2024-01-08 17:45 UTC, KatoToyoki approved these changes, later dismissed

2024-01-08 18:03 UTC, Error0229 approved these changes

2024-01-08 18:03 UTC, KatoToyoki approved these changes

2024-01-08 18:03 UTC, merged