[frontend] navbar distinguish roles
jykuo-love-shiritori/twp pull request #144
Opened 2024-01-07 17:50 UTC by KatoToyoki

Resolveeeeeeeees part of #94

### Changes & Testing Approach

### admin
- login with admin, the navbar looks like
  <img width="1246" alt="image" src="https://github.com/jykuo-love-shiritori/twp/assets/92158595/6af83fb2-df28-474c-8211-c2a6df8111d4">

### customer
- login with customer, the navbar looks like
  <img width="1246" alt="image" src="https://github.com/jykuo-love-shiritori/twp/assets/92158595/ab3b05b9-0ac9-4b24-aca4-a4a0caecf7b0">

### Test Environment Setup
open 3 terminals
one for `docker-compose up postgres minio `
one for `go run .`
one for `cd frontend` -> `npm i` -> `npm run build`
then open the browser then enter http://localhost:8080/ 

### Additional context

N/A

2024-01-07 18:41 UTC, UGisBusy commented
![image](https://github.com/jykuo-love-shiritori/twp/assets/91419313/2e2c3a45-31fb-4c6e-8612-7120a6d369c0)
in Admin pov, these options are needed?
this might need to Beckend check

2024-01-07 22:07 UTC, NOOBDY requested changes

2024-01-07 22:07 UTC, NOOBDY commented on frontend/src/components/NavBar.tsx
> +                    )}
```suggestion
                    ) : null}
```

2024-01-07 22:07 UTC, NOOBDY commented on frontend/src/components/NavBar.tsx
> +                    )}
you can also change to this somewhere down this component

2024-01-08 02:33 UTC, x06lan commented
> ![image](https://private-user-images.githubusercontent.com/91419313/294778458-2e2c3a45-31fb-4c6e-8612-7120a6d369c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODE0MzMsIm5iZiI6MTcwNDY4MTEzMywicGF0aCI6Ii85MTQxOTMxMy8yOTQ3Nzg0NTgtMmUyYzNhNDUtMzFmYi00YzZlLTg2MTItNzEyMGE2ZDM2OWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDAyMzIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0Mjc5MGI4NWEzNmMyODc3NGEwMzdmNGZlN2E1MDljOTE5YjdlNjkyNWQ5NWZlMGYzYzZkYjQ0Yjk5ODYzMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mcniBK9lGN7cafj0m4mCWpICY_uApLdLRIEr3IVn0bs) in Admin pov, these options are needed? this might need to Beckend check also, would be better if admin text is on the left side

the  security and order_history can remove but the personal info tab need to stay for change password admin image etc...

2024-01-08 02:51 UTC, KatoToyoki commented
> ![image](https://private-user-images.githubusercontent.com/91419313/294778458-2e2c3a45-31fb-4c6e-8612-7120a6d369c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODA2NTcsIm5iZiI6MTcwNDY4MDM1NywicGF0aCI6Ii85MTQxOTMxMy8yOTQ3Nzg0NTgtMmUyYzNhNDUtMzFmYi00YzZlLTg2MTItNzEyMGE2ZDM2OWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDAyMTkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllOWQ0Y2E2MGQ1NDM2YjkzNDQ2OTFkN2M3YmIwMDRlZGRiMWEzNTc1Yzg5ZjAxMGZkNzY3YTkzYWYzMTJhMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hOqOjMFoTzbTN9I08LCYHF5f7Rp9lk_-T-1vetgz_Kc) in Admin pov, these options are needed? this might need to Beckend check also, would be better if admin text is on the left side



> > ![image](https://private-user-images.githubusercontent.com/91419313/294778458-2e2c3a45-31fb-4c6e-8612-7120a6d369c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODE0MzMsIm5iZiI6MTcwNDY4MTEzMywicGF0aCI6Ii85MTQxOTMxMy8yOTQ3Nzg0NTgtMmUyYzNhNDUtMzFmYi00YzZlLTg2MTItNzEyMGE2ZDM2OWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDAyMzIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0Mjc5MGI4NWEzNmMyODc3NGEwMzdmNGZlN2E1MDljOTE5YjdlNjkyNWQ5NWZlMGYzYzZkYjQ0Yjk5ODYzMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mcniBK9lGN7cafj0m4mCWpICY_uApLdLRIEr3IVn0bs) in Admin pov, these options are needed? this might need to Beckend check also, would be better if admin text is on the left side
> 
> the security and order_history can remove but the personal info tab need to stay for change password admin image etc...

screen shots updated

2024-01-08 07:35 UTC, Error0229 submitted a review, later dismissed
WOMM

2024-01-08 16:21 UTC, NOOBDY submitted a review, later dismissed

2024-01-08 16:24 UTC, NOOBDY approved these changes

2024-01-08 16:28 UTC, Error0229 approved these changes

2024-01-08 16:29 UTC, merged