Password validation fix
jykuo-love-shiritori/twp pull request #148
Opened 2024-01-07 21:20 UTC by UGisBusy

Ex. Resolves #147 

### Changes
``[@$!%*?&\[\],.(){}":;'+\-=_~]`` all count toward special character n

### Testing Approach (if unconventional)
```sh
docker compose up --build
```

2024-01-07 22:35 UTC, NOOBDY submitted a review, later dismissed

2024-01-07 22:38 UTC, kryr34 requested changes
Update: https://github.com/jykuo-love-shiritori/twp/issues/147#issuecomment-1880200505

2024-01-08 09:15 UTC, Error0229 approved these changes
FINE

2024-01-08 10:55 UTC, x06lan approved these changes

2024-01-08 16:25 UTC, NOOBDY approved these changes

2024-01-08 20:04 UTC, kryr34 approved these changes
LGTM

2024-01-08 20:10 UTC, merged