[frontend] current progress : Home and Error, Login & Signup, Security
jykuo-love-shiritori/twp pull request #39
Opened 2023-11-16 16:27 UTC by KatoToyoki

## the interface of three sections are done :
Home and Error
- [ ] / (index)
- [ ] (401)
- [ ] (402)
- [ ] (403)

Login & Signup
- [ ] /login
- [ ] /signup

Security
- [ ] /user/security
- [ ] /user/security/password
- [ ] /user/security/manageCreditCard
- [ ] /user/security/manageCreditCard/new

## some progresses in sections but not done yet:

Discover & News
- [ ] /news/newsID

Info Settings
- [ ] /user/info

ViewShop
- [ ] /sellerID/shop

2023-11-17 08:26 UTC, UGisBusy commented on frontend/src/App.tsx
Routing pathes are a bit unconsistant.

At root level, somes pathes are relative while others are absolute.
(since they're at root level, both work the same)
```
<Route path='/user/seller/manageProducts/new' element={<NewGoods />} />
<Route path='sellerID/shop' element={<Shop />} />
```
At multiple layered, there're same issue too.
```
<Route path='user/buyer/order'>
  <Route path=':history_id' element={\<HistoryEach />} />
```
```
<Route path='user' element={<User />}>
  <Route path='/user/info' element={<Info />} />
```

2023-11-18 13:51 UTC, UGisBusy reviewed
Pls address the minor issues.
Other than that it's all good.
(i didn't check very hard in codes that is not part of the finished sections)

2023-11-18 13:51 UTC, UGisBusy commented on frontend/src/pages/discover/[goodsID].tsx
line 69:
> if (isGoodsExist) {

why not use ``!!foundGoods`` or ``foundGoods``

2023-11-18 13:51 UTC, UGisBusy commented on frontend/src/pages/news/[newsID].tsx
like one in the ``[goodsID].tsx``
line 31
>   if (isNewsExist) {

why not use ``!!foundNews`` or ``foundNews``

2023-11-18 13:51 UTC, UGisBusy commented on frontend/src/pages/user/seller/NewGoods.tsx
There're some unused code.
But this is not part of the finished section.
This will get fix, right?

2023-11-18 14:01 UTC, kryr34 commented on frontend/src/pages/user/seller/NewGoods.tsx
I suggest putting the `//TODO` everywhere to make sure everyone knows which parts are unfinished.

2023-11-18 14:04 UTC, KatoToyoki commented on frontend/src/pages/user/seller/NewGoods.tsx
i didn't finish this part at that time when you ask me to open a pull request so it's not finished yet,
and document man said that if i open a pull request, i shouldn't modify the code unless someone ask me to modify the code, so i just leave it here

2023-11-18 14:06 UTC, UGisBusy commented on frontend/src/pages/user/seller/NewGoods.tsx
Got it. Just to make sure and let everyone else know what's the deal of these codes.

2023-11-18 17:51 UTC, NOOBDY commented
does this PR also fix #22 and #23?

2023-11-18 17:55 UTC, NOOBDY commented
oh wait I am stupid

2023-11-18 18:06 UTC, NOOBDY requested changes

2023-11-18 18:06 UTC, NOOBDY commented on .gitignore
missing trailing newline here

2023-11-19 07:48 UTC, KatoToyoki commented
> does this PR also fix #22 and #23?

fixed it and linked the issues

2023-11-19 13:13 UTC, NOOBDY commented
#22 still remains broken when going to previous page, I don't know if this could even be fixed due to how SPA works, but I think that issue should still remain open and we can merge this PR for now

2023-11-19 13:23 UTC, NOOBDY commented
entering some product page
![image](https://github.com/jykuo-love-shiritori/twp/assets/48180490/1ec453b7-2715-4311-8b3b-7159dd163662)
browsing product page then go back
![image](https://github.com/jykuo-love-shiritori/twp/assets/48180490/d90d42ff-4125-48ac-84f5-3443d84d387d)
page at wrong location
![image](https://github.com/jykuo-love-shiritori/twp/assets/48180490/de136cc4-2bcb-4547-b074-cc6396fdf7c7)

2023-11-19 13:30 UTC, NOOBDY requested changes
LGTM otherwise https://github.com/jykuo-love-shiritori/twp/pull/39#discussion_r1398246222

2023-11-21 06:09 UTC, NOOBDY approved these changes
LGTM

2023-11-21 06:13 UTC, merged