[frontend] check ViewShop & Order section
jykuo-love-shiritori/twp pull request #61
Opened 2023-11-24 10:56 UTC by KatoToyoki

Ex. Check progress #13 

### Changes & Testing Approach

please check the following instances

### (E) ViewShop 
- [x] [/sellerID/shop](http://localhost:5173/sellerID/shop)
    - check left buttons are direct to right path
- [x] [/seller/manageProducts](http://localhost:5173/user/seller/manageProducts)
    - check left buttons are direct to right path
    - view interface
- [x] [/seller/manageProducts/new](http://localhost:5173/user/seller/manageProducts/new)
    - check left buttons are direct to right path
    - view interface
    - click upload img button and try to upload img
    - try to input some tags
- [x] [/seller/manageProducts/productID](http://localhost:5173/user/seller/manageProducts/1)
    - check left buttons are direct to right path
    - view interface with existed goods
    - click upload img button and try to update img
    - try to input some new tags and modify old tags
    - try change information on right sides

### (F) Order 
- [x] [/buyer/order](http://localhost:5173/user/buyer/order)
    - check left buttons are direct to right path
    - view interface
- [x] [/buyer/order/orderID](http://localhost:5173/user/buyer/order/3)
    - check left buttons are direct to right path
    - view interface, check if it's right path
- [x] [/seller/order/orderID](http://localhost:5173/user/seller/order/3)
    - check left buttons are direct to right path
    - view interface, check if it's right path
- [x] [/seller/order](http://localhost:5173/user/seller/orders)
    - check left buttons are direct to right path
    - view interface

### Additional context

N/A

2023-11-25 14:59 UTC, NOOBDY requested changes
[`/seller/manageProducts`](http://localhost:5173/user/seller/manageProducts) has wrong page width

all password input boxes are in plain text

2023-11-25 20:18 UTC, NOOBDY approved these changes, later dismissed

2023-11-27 08:15 UTC, UGisBusy commented
Should the url be ``/sellerID/shop`` with literal words "sellerID" (not the number like ``/1/shop``) ?

2023-11-27 08:47 UTC, UGisBusy requested changes
LGTM besides the off-center issue.

2023-11-27 08:47 UTC, UGisBusy commented on frontend/src/components/HistoryItem.tsx
In pages like [seller/order](http://localhost:5173/user/seller/order/3), [buyer/order](http://localhost:5173/user/buyer/order) and other pages that use ``HistoryItem`` component.
The words are off-center vertically. You can scale the page very small to make it obvious.

line 40-45,
```
<Col xs={2} md={2} className='center'>
	<img src={firstItem?.imgUrl} style={{ width: '70px' }} />
/Col>
<Col xs={4} md={4} className='center_vertical'>
	{firstItem?.name}
</Col>
```
The ``center_vertical`` does nothing since its parent is very small.

2023-11-27 10:55 UTC, KatoToyoki commented
> Should the url be `/sellerID/shop` with literal words "sellerID" (not the number like `/1/shop`) ?

i will leave it for functionality, now for interface i just want to make sure the interface looks right.

2023-11-27 11:16 UTC, x06lan commented
## RWD need fix
![screenshot-2023-11-27-19-12-24](https://github.com/jykuo-love-shiritori/twp/assets/52856456/bb66b286-fba4-41f2-b427-e0b7c0c83c9d)
## image radius border
![](https://cdn.discordapp.com/attachments/907634185743765506/1178653246303260702/image.png?ex=6576ed60&is=65647860&hm=1f7ffde3ad313025b5f7915a540ea8bf3bb32a64d6ba2c2fb07d59166bd84942&)

2023-11-27 15:18 UTC, x06lan approved these changes

2023-11-27 19:38 UTC, NOOBDY approved these changes

2023-11-28 09:33 UTC, UGisBusy approved these changes

2023-11-28 09:35 UTC, merged