Oauth2
jykuo-love-shiritori/twp pull request #80
Opened 2023-12-06 06:27 UTC by NOOBDY

Resolves #46 

### Changes

TODO Listed in issue

### Testing Approach (if unconventional)

- Go to `/signup` and register an user
- Go to `/login` and click on the button
- Enter your login credentials
- After being redirected to the home page you should see your access token if you open the dev console

### Additional context

N/A

2023-12-11 17:57 UTC, Error0229 commented
Test failed when clicked login button, got `ERR_CONNECTION_REFUSED`
Request
```
curl 'http://localhost:5173/authorize?client_id=twp&code_challenge=p0-SBpejdZ0AuRVuQxSsmw5u25j9Ra05JF8E5uFPFv0&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fcallback&response_type=code&state=NjQzNTgxNjU4MzU5NDMwNTQ4OTI1NjIzMjUxNzExNzIzNDg0NjUyNTA2NjMxNzA5MzIwNDg0ODQzMTk2NDY1MDYwODM2MDkyNTUxODU' \
  -H 'Referer: http://localhost:8080/' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0' \
  -H 'sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Microsoft Edge";v="120"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  --compressed
```

Log
```
twp-twp-1       | {"level":"error","ts":1702316687.702742,"caller":"auth/refresh.go:17","msg":"http: named cookie not present","stacktrace":"github.com/jykuo-love-shiritori/twp/pkg/router.RegisterApi.Refresh.func7\n\t/app/pkg/auth/refresh.go:17\ngithub.com/labstack/echo/v4.(*Echo).add.func1\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.11.2/echo.go:582\ngithub.com/labstack/echo/v4/middleware.StaticWithConfig.func1.1\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.11.2/middleware/static.go:167\ngithub.com/labstack/echo/v4/middleware.RequestLoggerConfig.ToMiddleware.func1.1\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.11.2/middleware/request_logger.go:259\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.11.2/echo.go:669\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2938\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2009"}
twp-twp-1       | {"level":"info","ts":1702316687.7028463,"caller":"app/logger.go:15","msg":"request","method":"POST","URI":"/api/oauth/refresh","status":401}
twp-twp-1       | {"level":"info","ts":1702316687.7036245,"caller":"app/logger.go:15","msg":"request","method":"GET","URI":"/assets/logo-28e599d4.png","status":200}
twp-twp-1       | {"level":"error","ts":1702316687.7264962,"caller":"auth/refresh.go:17","msg":"http: named cookie not present","stacktrace":"github.com/jykuo-love-shiritori/twp/pkg/router.RegisterApi.Refresh.func7\n\t/app/pkg/auth/refresh.go:17\ngithub.com/labstack/echo/v4.(*Echo).add.func1\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.11.2/echo.go:582\ngithub.com/labstack/echo/v4/middleware.StaticWithConfig.func1.1\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.11.2/middleware/static.go:167\ngithub.com/labstack/echo/v4/middleware.RequestLoggerConfig.ToMiddleware.func1.1\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.11.2/middleware/request_logger.go:259\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.11.2/echo.go:669\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2938\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2009"}
twp-twp-1       | {"level":"info","ts":1702316687.7265587,"caller":"app/logger.go:15","msg":"request","method":"POST","URI":"/api/oauth/refresh","status":401}
twp-twp-1       | {"level":"info","ts":1702316687.729732,"caller":"app/logger.go:15","msg":"request","method":"GET","URI":"/assets/login-22840771.jpg","status":200}
```

2023-12-12 12:44 UTC, Error0229 requested changes

2023-12-12 12:44 UTC, Error0229 commented on db/queries/user.sql
> +    OR "email" = $1;
since it seems only allow login with email, the sql only need email as input

2023-12-12 12:44 UTC, Error0229 commented on db/queries/user.sql
> +    OR "email" = $1;
consider add some comment

2023-12-13 08:25 UTC, Error0229 requested changes

2023-12-13 08:25 UTC, Error0229 commented on pkg/auth/token.go
remove debug codes

2023-12-13 08:25 UTC, Error0229 commented on pkg/auth/verify_test.go
should this move to `test/auth`?

2023-12-13 08:30 UTC, NOOBDY commented on pkg/auth/verify_test.go
this is a unit test that can be ran without human intervention or in CI, the `./test/...` are integration tests meant to be ran manually and sometimes would require interactions

2023-12-13 08:33 UTC, NOOBDY commented on pkg/auth/token.go
fixed

2023-12-13 09:14 UTC, Error0229 approved these changes, later dismissed
Backend part LGTM

2023-12-14 11:54 UTC, Error0229 commented
Is it normal that the invalid email/password login redirect to `http://localhost:8080/callback?state=undefined&code=undefined` ?Also that path is a empty page
The valid email/password login functions are works fine anyway.

2023-12-14 12:31 UTC, NOOBDY commented
the `/callback` page is supposed to be empty, but I don't know what the behavior should be when the user inputs so I'll leave that to the frontend team

2023-12-14 13:10 UTC, UGisBusy commented
I think the frontend can provide least amount of verification, i.e. email most contain @, every slot must not be empty.
This way gets little more UX then what it is right now imo.

2023-12-14 14:55 UTC, Error0229 approved these changes

2023-12-14 17:19 UTC, UGisBusy approved these changes
lgtm

2023-12-15 08:14 UTC, merged