[backend] update schema
jykuo-love-shiritori/twp pull request #84
Opened 2023-12-06 12:23 UTC by Error0229

Resolves #83 

### Changes

- Add coupon scope `{'global', 'shop'}` in `"coupon"` table (actually done in previous PR)
- Add `image_id` for "order_history" as thumbnail.
- Add `sqlc`'s `go_type` override UUID as string while constructing struct
- Modify `test/main.go` to fit changes above

### Testing Approach 

```bash
docker-compose up postgres
migrate -path db/migrations/ -database $POSTGRESQL_URL down #if the previous one not down yet
migrate -path db/migrations/ -database $POSTGRESQL_URL up
go run ./test
migrate -path db/migrations/ -database $POSTGRESQL_URL down 
```

### Additional context

N/A

2023-12-06 12:47 UTC, x06lan submitted a review, later dismissed

2023-12-06 16:39 UTC, NOOBDY requested changes

2023-12-06 16:39 UTC, NOOBDY commented on pkg/auth/signup.go
> +			ImageID:  "00000000-0000-0000-0000-000000000000",
if user image is no longer a required field, you can modify the query to not include this

2023-12-06 16:44 UTC, NOOBDY commented on pkg/auth/signup.go
> +			ImageID:  "00000000-0000-0000-0000-000000000000",
you should also remove this in `user.sql`

2023-12-07 03:43 UTC, NOOBDY approved these changes

2023-12-07 04:41 UTC, x06lan approved these changes

2023-12-07 04:41 UTC, merged