[frontend] Cart Section
jykuo-love-shiritori/twp pull request #89
Opened 2023-12-09 10:49 UTC by UGisBusy

Reeeeesolves #13 partially

### Changes

### (G) Cart 
- [x ] [/buyer/cart](http://localhost:5173/buyer/cart) 

Navigate: 
- click the cart icon on nav bar
- use [url](http://localhost:5173/buyer/cart) 

Function:
- most butions will print something to console. will change to use api later.
- click ``checkout`` button in the cart**s** view will bring up ``chekcout`` section of this cart.
- click ``+`` by the discount will bring up ``usable coupon``  selection.

### Testing Approach (if unconventional)

- open frontend server
  ```sh
  cd frontend
  npm run dev
  ```
- go the the new page

### Additional context

- The checkout section will show one of the same cart because there're only one mocked data.
- Buttons change nothing in ui because it only refetches data and the mocked data cant be modify obviously.
- Credit card selection on checkout page is wip because the api doc man fogor.
- No idea how to handle status code other ok in ``useQuery``. Currently i just link to error pages. Pls give advice if u have any ❤️

2023-12-10 06:14 UTC, KatoToyoki requested changes
<img width="592" alt="image" src="https://github.com/jykuo-love-shiritori/twp/assets/92158595/226c3bae-f253-4b2b-a6fa-955882d632e9">
<img width="634" alt="image" src="https://github.com/jykuo-love-shiritori/twp/assets/92158595/8657e460-11bc-43c8-9cf5-368e394c668c">

this part in checkout, the discount reveals the chosen ones while the modal reveals the available but unchosen ones could be more intuitive for users.

2023-12-10 19:45 UTC, NOOBDY requested changes

2023-12-10 19:45 UTC, NOOBDY commented on frontend/src/components/CouponItemTemplate.tsx
> +  witdh: '100%',
```suggestion
  width: '100%',
```

2023-12-10 19:45 UTC, NOOBDY commented on frontend/src/components/Cart.tsx
> +  scope: string; // 'global' | 'shop'
```suggestion
  type: 'percentage' | 'fixed' | 'shipping';
  scope: 'global' | 'shop';
```

2023-12-10 19:45 UTC, NOOBDY commented on frontend/src/pages/user/buyer/cart/index.tsx
> +import CartGroup from '@components/Cart';
```suggestion
import Cart from '@components/Cart';
```

2023-12-10 19:45 UTC, NOOBDY commented on frontend/src/pages/user/buyer/history/[historyID].tsx
> +import CartItem from '@components/CartProduct';
```suggestion
import CartProduct from '@components/CartProduct';
```

2023-12-18 10:51 UTC, KatoToyoki requested changes

2023-12-18 10:51 UTC, KatoToyoki commented on frontend/src/components/Cart.tsx
> +import CheckoutItemCoupon from './CheckoutItemCoupon';
here should use `@components/` rather than `./`, otherwise lgtm

2023-12-19 07:36 UTC, KatoToyoki submitted a review, later dismissed

2023-12-20 04:10 UTC, KatoToyoki submitted a review, later dismissed

2023-12-21 05:53 UTC, NOOBDY approved these changes

2023-12-21 06:18 UTC, KatoToyoki approved these changes

2023-12-21 06:29 UTC, merged