[frontend] Sign Up api
jykuo-love-shiritori/twp pull request #96
Opened 2023-12-21 18:26 UTC by UGisBusy

Ex. Resolves #94 

### Changes

#### Page
- [x] [/signup](http://localhost:8080/signup)

#### APIs
- Customer signup

#### Function
- the account data have these constraints:
  - email: need to be an email
  - username: only english letter and number, less than 32 characters
  - name: no constraint
  - password: contain at least one upper case, one lower case, one number and one special character, 8 to 72 characters
- if some contraints are not fullfilled, it shouldnt send the data
- if all  contraints are fullfilled
  - will navigate to login and this means it success
  - will pop up warning modal that show the error from backend. (duplicated email or username)

### Testing Approach (if unconventional)
```sh
docker compose up --build
```
- Create a acount in signup
  - test all cases
- Try login

### Additional context
I change some oauth-related codes. 
May get them all done (login page api and error handling) to this pr.
Or merge signup first. Depend on how hard i suffer.

2023-12-24 17:56 UTC, NOOBDY requested changes

2023-12-24 17:56 UTC, NOOBDY commented on frontend/src/lib/Status.tsx
should this be a `.tsx` file?

2023-12-24 17:56 UTC, NOOBDY commented on frontend/src/lib/Status.tsx
> +export const RouteOnNotOK = (responce: Response, navigate: NavigateFunction) => {
```suggestion
export const RouteOnNotOK = (response: Response, navigate: NavigateFunction) => {
```
I would suggest you install a spell checker tool

2023-12-24 17:56 UTC, NOOBDY commented on frontend/src/pages/user/signup.tsx
> +                    <FormItem label='Password'>
```suggestion
                    <FormItem label='password'>
```

2023-12-24 17:56 UTC, NOOBDY commented on frontend/src/pages/user/authorize.tsx
> +  const body = Object.fromEntries([...searchParams.entries()]);
```suggestion
  const body = Object.fromEntries(searchParams.entries());
```

2023-12-24 17:56 UTC, NOOBDY commented on frontend/src/pages/user/callback.tsx
>    if (error) {
```suggestion
  const { isPending, isError, data, refetch } = useQuery({
    queryKey: ['token'],
    queryFn: getToken,
    enabled: false,
  });

  if (!code || !state || !verifier) {
    console.log('Missing code, state or verifier');
    return <Navigate to='/login' replace={true} />;
  }

  refetch();
  if (isPending) {
    return <>Loading</>;
  }

  if (isError) {
```
i think i effed up before

2023-12-24 21:06 UTC, UGisBusy commented on frontend/src/lib/Status.tsx
Status.tsx will have this component after mergin main.
```tsx
export const CheckFetchStatus = ({ status }: FetchStatusProps) => {
  switch (status) {
    case 'pending':
      return <div>Loading...</div>;
    case 'error':
      return <div>Error...</div>;
  }
};
```
Or do u think putting them in the same file is bad?

2023-12-25 02:37 UTC, KatoToyoki reviewed
<img width="717" alt="image" src="https://github.com/jykuo-love-shiritori/twp/assets/92158595/76da6c18-9445-4295-ab80-c4ba294fd680">

is it normal that when i sign up with a new account then login, encounter of the situation of 401?
edge, safari and firefox all have this

edit:
after reloading the page it will disappear but it always appears when first login

2023-12-25 04:38 UTC, UGisBusy commented
I think one is when u first enter the website. 
And second is when u sign upped, navigate back to ``login``, than click the login button.
It's likely that this in intended imo.

2023-12-26 04:47 UTC, KatoToyoki approved these changes

2023-12-26 06:14 UTC, NOOBDY approved these changes

2023-12-26 08:24 UTC, merged